export const content = {
  en: {
    name: "Mojib Rsm",
    tagline: "Creative Developer & UI/UX Enthusiast",
    heroButton: "Explore My Work",
    navHome: "Home",
    navAbout: "About",
    navProjects: "Projects",
    navTools: "Tools",
    navContact: "Contact",
    cvButton: "Download CV",
    servicesTitle: "What I Do",
    projectsTitle: "My Creations",
    testimonialsTitle: "What Clients Say",
    achievementsTitle: "My Achievements",
    faqTitle: "Frequently Asked Questions",
    footerText: "Let's build something amazing together.",
    newsletterTitle: "Join My Newsletter",
    newsletterPlaceholder: "Enter your email",
    newsletterButton: "Subscribe",
    toolsTitle: "Tools Hub",
    qrGeneratorTitle: "QR Code Generator",
    textFormatterTitle: "AI Text Formatter",
    imageCompressorTitle: "Image Compressor",
    domainCheckerTitle: "Domain Checker",
    qrInputPlaceholder: "Enter text or URL",
    qrGenerateButton: "Generate QR",
    textFormatterInputLabel: "Your Text",
    textFormatterOutputLabel: "Formatted Text",
    textFormatterButton: "Format Text",
    textFormatterLoading: "Formatting...",
    allProjects: "All",
    faq1_q: "What services do you offer?",
    faq1_a: "I offer a range of services including web development, UI/UX design, and mobile app development. My focus is on creating beautiful, functional, and user-friendly digital experiences.",
    faq2_q: "What technologies do you work with?",
    faq2_a: "I'm proficient in a variety of modern technologies including Next.js, React, Tailwind CSS, TypeScript, and Framer Motion. I'm always learning and adapting to new tools.",
    faq3_q: "How can I start a project with you?",
    faq3_a: "The best way to start is by sending me a message through the contact form. We can schedule a call to discuss your project in detail.",
  },
  bn: {
    name: "মুজিব রসম",
    tagline: "সৃজনশীল ডেভেলপার এবং UI/UX উত্সাহী",
    heroButton: "আমার কাজ দেখুন",
    navHome: "হোম",
    navAbout: "সম্পর্কে",
    navProjects: "প্রকল্প",
    navTools: "টুলস",
    navContact: "যোগাযোগ",
    cvButton: "সিভি ডাউনলোড করুন",
    servicesTitle: "আমি যা করি",
    projectsTitle: "আমার সৃষ্টি",
    testimonialsTitle: "ক্লায়েন্টরা যা বলেন",
    achievementsTitle: "আমার অর্জন",
    faqTitle: "সচরাচর জিজ্ঞাসিত প্রশ্ন",
    footerText: "আসুন একসাথে অসাধারণ কিছু তৈরি করি।",
    newsletterTitle: "আমার নিউজলেটারে যোগ দিন",
    newsletterPlaceholder: "আপনার ইমেল লিখুন",
    newsletterButton: "সাবস্ক্রাইব করুন",
    toolsTitle: "টুলস হাব",
    qrGeneratorTitle: "QR কোড জেনারেটর",
    textFormatterTitle: "এআই টেক্সট ফরমেটার",
    imageCompressorTitle: "ইমেজ কম্প্রেসার",
    domainCheckerTitle: "ডোমেইন চেকার",
    qrInputPlaceholder: "টেক্সট বা ইউআরএল লিখুন",
    qrGenerateButton: "QR তৈরি করুন",

    textFormatterInputLabel: "আপনার টেক্সট",
    textFormatterOutputLabel: "ফরম্যাট করা টেক্সট",
    textFormatterButton: "টেক্সট ফরম্যাট করুন",
    textFormatterLoading: "ফরম্যাটিং চলছে...",
    allProjects: "সব",
    faq1_q: "আপনি কি কি সেবা প্রদান করেন?",
    faq1_a: "আমি ওয়েব ডেভেলপমেন্ট, UI/UX ডিজাইন, এবং মোবাইল অ্যাপ ডেভেলপমেন্ট সহ বিভিন্ন সেবা প্রদান করি। আমার লক্ষ্য সুন্দর, কার্যকরী, এবং ব্যবহারকারী-বান্ধব ডিজিটাল অভিজ্ঞতা তৈরি করা।",
    faq2_q: "আপনি কোন প্রযুক্তি নিয়ে কাজ করেন?",
    faq2_a: "আমি Next.js, React, Tailwind CSS, TypeScript, এবং Framer Motion সহ বিভিন্ন আধুনিক প্রযুক্তিতে দক্ষ। আমি সবসময় নতুন সরঞ্জাম শিখছি এবং মানিয়ে নিচ্ছি।",
    faq3_q: "আমি আপনার সাথে কিভাবে একটি প্রকল্প শুরু করতে পারি?",
    faq3_a: "শুরু করার সেরা উপায় হল যোগাযোগ ফর্মের মাধ্যমে আমাকে একটি বার্তা পাঠানো। আমরা আপনার প্রকল্প বিস্তারিত আলোচনা করার জন্য একটি কল নির্ধারণ করতে পারি।",
  },
};
